### ISSUE TITLE
Ridiculous Mob Spawning

### ISSUE THREAD

**Issue by Zodsmar** [Shukaro/Artifice#105]
Artiifice is causing masses of mobs to spawn. An example is I find a chunk completely full of chickens, or sheep. Like what. Its causing a lot of lag to worlds.

**Comment by enkryptor** [comment]
How can you be sure it's because of Artifice? AFAIK it doesn't affect animal spawning.

**Comment by Revemohl** [comment]
Chunks ridiculously filled with one kind of entity is a common side-effect of corrupted chunks. Have you checked if removing Artifice makes the problem go away, or if those chunks are working properly?

**Comment by Zodsmar** [comment]
I have removed Artifice and it seems to be fixed which is why I am pretty sure its artifice. However what causes Chunk Corruption normally and can it be fixed?
