### ISSUE TITLE
Tick Handler issue

### ISSUE THREAD

**Issue by GreatOrator** [Shukaro/Artifice#108]
Not exactly sure what caused this crash, but seems to be related to tick handling.

http://pastebin.com/MA02zXqr

**Comment by Shukaro** [comment]
Interesting, has it happened more than once?

**Comment by GreatOrator** [comment]
I personally have not been able to recreate it, but have had a couple other reports with no logs.

Honestly could have been a one-off (you know how minecraft can be sometimes) but will actively search out any other crash logs.

Thankfully I use openeye and yampst so just might be able to.

**Comment by GreatOrator** [comment]
I'll comb through the yampst and openeye logs to see if I can find anymore...could honestly have been a one-off (you know minecraft)

**Comment by Shukaro** [comment]
Closing for the time being
