### ISSUE TITLE
Crash when using anvil

### ISSUE THREAD

**Issue by Revemohl** [Shukaro/Artifice#112]
Getting this whenever I use an anvil, place an item that can be repaired in the first slot, then something that can repair it in the second slot: http://pastebin.com/sUpVCfGY
(Tested with iron swords and iron ingots, got the crash 100% of the time)
Looks like this has been happening ever since build 345, up until at least 389. Couldn't check on 390 or 391 because I'm getting "The page cannot be displayed because an internal server error has occurred." when I try to download from the Curse page.

**Comment by Shukaro** [comment]
Fixed by e2a9e3d4f57f93454efced54e8b53537b0f8ef26
