### ISSUE TITLE
Uranium Ore and Nuclear Stirling Battery textures missing

### ISSUE THREAD

**Issue by jermangarc** [Shukaro/Artifice#115]
I was able to fix the Uranium Ores, but was wondering if you had the texture for the Sterling Battery. If you'd like I would be more than happy to help as I'm a graphic artist. The logs show the sterling battery textures missing which show different charge states.

**Comment by Shukaro** [comment]
You're using an out-dated version

**Comment by jermangarc** [comment]
Oops! :) Sorry about that. Guess I should check Curse next time.
