### ISSUE TITLE
Crash while using a regular minecraft anvil

### ISSUE THREAD

**Issue by abidoang** [Shukaro/Artifice#116]
So I was trying to combine my iron pickaxe with a Fortune III enchanted book in a normal anvil. I put my pickaxe in the first slot. But when I put the book on the second slot, the game crashed. Here's the crash report: http://pastebin.com/FSAW6DyC

Artifice was mentioned in the log. OpenEye also informed that artifice is involved in the crash

**Comment by Shukaro** [comment]
Update artifice
