### ISSUE TITLE
[Mod Bug]: Breaking All "Double Slab" blocks 

### ISSUE THREAD

**Issue by Lanse505** [Shukaro/Artifice#84]
Mod Version: ARTIFICE-1.7-1.1.4-304
Artifice Only: Yes
Issue: Whenever you place 2 of any artifice slabs ontop of each other turning it to a "double-slab" and then break it, it drops 2 Double Slab Blocks instead of 2 slabs.

**Comment by enkryptor** [comment]
I can confirm it with the latest version.

**Comment by Shukaro** [comment]
Fixed by dbd972f7377a50bf210585a5b64c871dba3d32ba

**Comment by enkryptor** [comment]
good job!
