### ISSUE TITLE
Block Glitch

### ISSUE THREAD

**Issue by nastyman99** [Shukaro/Artifice#90]
I don't know if this is just me, but when i try and use the mod all the blocks are invisible. Now i don't know if its the code or im doing something wrong but i have CoFHCore installed and this mod does not seem to be compatible with one of these: Flans, Journeymap, MCHeli, inventory tweaks, lunatrious core, NEI, optifine or schematica. Please Help.

**Comment by jermangarc** [comment]
Which version of Optifine are you using?

**Comment by Shukaro** [comment]
It's optifine.
