### ISSUE TITLE
Min and Max Layer Height of Limestone is getting reset to default 60/70 values.

### ISSUE THREAD

**Issue by sircrimer** [Shukaro/Artifice#95]
Im using build 313. This is the part of the config that i was trying to use.

		"layer generation" {
			B:"Generate BasaltLayer"=true
			B:"Generate Blue LimestoneLayer"=true
			B:"Generate Brown LimestoneLayer"=true
			B:"Generate Gray LimestoneLayer"=true
			B:"Generate Green LimestoneLayer"=true
			B:"Generate Light Gray LimestoneLayer"=true
			B:"Generate MarbleLayer"=false
			B:"Generate Red LimestoneLayer"=true
			B:"Generate Tan LimestoneLayer"=true
			I:"Maximum Basalt Layer Height"=10
			I:"Maximum Blue Limestone Layer Height"=66
			I:"Maximum Brown Limestone Layer Height"=58
			I:"Maximum Gray Limestone Layer Height"=60
			I:"Maximum Green Limestone Layer Height"=68
			I:"Maximum Light Gray Limestone Layer Height"=62
			I:"Maximum Marble Layer Height"=70
			I:"Maximum Red Limestone Layer Height"=70
			I:"Maximum Tan Limestone Layer Height"=64
			I:"Minimum Basalt Layer Height"=0
			I:"Minimum Blue Limestone Layer Height"=65
			I:"Minimum Brown Limestone Layer Height"=57
			I:"Minimum Gray Limestone Layer Height"=59
			I:"Minimum Green Limestone Layer Height"=67
			I:"Minimum Light Gray Limestone Layer Height"=61
			I:"Minimum Marble Layer Height"=60
			I:"Minimum Red Limestone Layer Height"=69
			I:"Minimum Tan Limestone Layer Height"=63
		}

It got changed to this:

"layer generation" {
    B:"Generate BasaltLayer"=true
    B:"Generate Blue LimestoneLayer"=true
    B:"Generate Brown LimestoneLayer"=true
    B:"Generate Gray LimestoneLayer"=true
    B:"Generate Green LimestoneLayer"=true
    B:"Generate Light Gray LimestoneLayer"=true
    B:"Generate MarbleLayer"=false
    B:"Generate Red LimestoneLayer"=true
    B:"Generate Tan LimestoneLayer"=true
    I:"Maximum Basalt Layer Height"=10
    I:"Maximum Blue Limestone Layer Height"=70
    I:"Maximum Brown Limestone Layer Height"=70
    I:"Maximum Gray Limestone Layer Height"=70
    I:"Maximum Green Limestone Layer Height"=70
    I:"Maximum Light Gray Limestone Layer Height"=70
    I:"Maximum Marble Layer Height"=70
    I:"Maximum Red Limestone Layer Height"=70
    I:"Maximum Tan Limestone Layer Height"=70
    I:"Minimum Basalt Layer Height"=0
    I:"Minimum Blue Limestone Layer Height"=60
    I:"Minimum Brown Limestone Layer Height"=60
    I:"Minimum Gray Limestone Layer Height"=60
    I:"Minimum Green Limestone Layer Height"=60
    I:"Minimum Light Gray Limestone Layer Height"=60
    I:"Minimum Marble Layer Height"=60
    I:"Minimum Red Limestone Layer Height"=60
    I:"Minimum Tan Limestone Layer Height"=60
}

**Comment by Shukaro** [comment]
I just tried to reproduce this and couldn't. Perhaps you forgot to save it, or there's some other wonkinesss going on?

**Comment by sircrimer** [comment]
I tested it again and it works now. Derpiness on my part.
